# Generated by Django 2.2.16 on 2022-08-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220802_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
